name: foto_share
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable:
  flutter_bloc:
  firebase_auth:
  firebase_core:
  firebase_storage:
  google_sign_in:
  cloud_firestore:
  flutter_shimmer:
  flutterfire_ui:
  image_picker:
  path_provider: ^2.0.9
  share_plus: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
